"module: access-context-manager":
  - changed-files:
      - any-glob-to-any-file: 'modules/access-context-manager/**'

"module: alloydb":
  - changed-files:
      - any-glob-to-any-file: 'modules/alloydb/**'

"module: analytics-hub":
  - changed-files:
      - any-glob-to-any-file: 'modules/analytics-hub/**'

"module: api-gateway":
  - changed-files:
      - any-glob-to-any-file: 'modules/api-gateway/**'

"module: apigee":
  - changed-files:
      - any-glob-to-any-file: 'modules/apigee/**'

"module: app-engine":
  - changed-files:
      - any-glob-to-any-file: 'modules/app-engine/**'

"module: artifact-registry":
  - changed-files:
      - any-glob-to-any-file: 'modules/artifact-registry/**'

"module: beyondcorp":
  - changed-files:
      - any-glob-to-any-file: 'modules/beyondcorp/**'

"module: biglake-catalog":
  - changed-files:
      - any-glob-to-any-file: 'modules/biglake-catalog/**'

"module: bigquery-dataset":
  - changed-files:
      - any-glob-to-any-file: 'modules/bigquery-dataset/**'

"module: bigtable-instance":
  - changed-files:
      - any-glob-to-any-file: 'modules/bigtable-instance/**'

"module: billing-account":
  - changed-files:
      - any-glob-to-any-file: 'modules/billing-account/**'

"module: binauthz":
  - changed-files:
      - any-glob-to-any-file: 'modules/binauthz/**'

"module: certificate-authority-service":
  - changed-files:
      - any-glob-to-any-file: 'modules/certificate-authority-service/**'

"module: certificate-manager":
  - changed-files:
      - any-glob-to-any-file: 'modules/certificate-manager/**'

"module: cis-log-alerts":
  - changed-files:
      - any-glob-to-any-file: 'modules/cis-log-alerts/**'

"module: cis-log-metrics":
  - changed-files:
      - any-glob-to-any-file: 'modules/cis-log-metrics/**'

"module: cloud-config-container":
  - changed-files:
      - any-glob-to-any-file: 'modules/cloud-config-container/**'

"module: cloud-function-v1":
  - changed-files:
      - any-glob-to-any-file: 'modules/cloud-function-v1/**'

"module: cloud-function-v2":
  - changed-files:
      - any-glob-to-any-file: 'modules/cloud-function-v2/**'

"module: cloud-identity-group":
  - changed-files:
      - any-glob-to-any-file: 'modules/cloud-identity-group/**'

"module: cloud-run":
  - changed-files:
      - any-glob-to-any-file: 'modules/cloud-run/**'

"module: cloud-run-v2":
  - changed-files:
      - any-glob-to-any-file: 'modules/cloud-run-v2/**'

"module: cloud-run-v2-se":
  - changed-files:
      - any-glob-to-any-file: 'modules/cloud-run-v2-se/**'

"module: cloud-scheduler":
  - changed-files:
      - any-glob-to-any-file: 'modules/cloud-scheduler/**'

"module: cloudsql-instance":
  - changed-files:
      - any-glob-to-any-file: 'modules/cloudsql-instance/**'

"module: compute-mig":
  - changed-files:
      - any-glob-to-any-file: 'modules/compute-mig/**'

"module: compute-vm":
  - changed-files:
      - any-glob-to-any-file: 'modules/compute-vm/**'

"module: container-registry":
  - changed-files:
      - any-glob-to-any-file: 'modules/container-registry/**'

"module: data-catalog-policy-tag":
  - changed-files:
      - any-glob-to-any-file: 'modules/data-catalog-policy-tag/**'

"module: data-catalog-tag":
  - changed-files:
      - any-glob-to-any-file: 'modules/data-catalog-tag/**'

"module: data-catalog-tag-template":
  - changed-files:
      - any-glob-to-any-file: 'modules/data-catalog-tag-template/**'

"module: dataform-repository":
  - changed-files:
      - any-glob-to-any-file: 'modules/dataform-repository/**'

"module: datafusion":
  - changed-files:
      - any-glob-to-any-file: 'modules/datafusion/**'

"module: datafusion-se":
  - changed-files:
      - any-glob-to-any-file: 'modules/datafusion-se/**'

"module: dataplex":
  - changed-files:
      - any-glob-to-any-file: 'modules/dataplex/**'

"module: dataplex-datascan":
  - changed-files:
      - any-glob-to-any-file: 'modules/dataplex-datascan/**'

"module: dataproc":
  - changed-files:
      - any-glob-to-any-file: 'modules/dataproc/**'

"module: dns":
  - changed-files:
      - any-glob-to-any-file: 'modules/dns/**'

"module: dns-response-policy":
  - changed-files:
      - any-glob-to-any-file: 'modules/dns-response-policy/**'

"module: endpoints":
  - changed-files:
      - any-glob-to-any-file: 'modules/endpoints/**'

"module: firestore":
  - changed-files:
      - any-glob-to-any-file: 'modules/firestore/**'

"module: folder":
  - changed-files:
      - any-glob-to-any-file: 'modules/folder/**'

"module: gcs":
  - changed-files:
      - any-glob-to-any-file: 'modules/gcs/**'

"module: gcve-private-cloud":
  - changed-files:
      - any-glob-to-any-file: 'modules/gcve-private-cloud/**'

"module: gke-cluster-autopilot":
  - changed-files:
      - any-glob-to-any-file: 'modules/gke-cluster-autopilot/**'

"module: gke-cluster-standard":
  - changed-files:
      - any-glob-to-any-file: 'modules/gke-cluster-standard/**'

"module: gke-cluster-standard-se":
  - changed-files:
      - any-glob-to-any-file: 'modules/gke-cluster-standard-se/**'

"module: gke-hub":
  - changed-files:
      - any-glob-to-any-file: 'modules/gke-hub/**'

"module: gke-nodepool":
  - changed-files:
      - any-glob-to-any-file: 'modules/gke-nodepool/**'

"module: iam-service-account":
  - changed-files:
      - any-glob-to-any-file: 'modules/iam-service-account/**'

"module: intrusion-detection-system":
  - changed-files:
      - any-glob-to-any-file: 'modules/intrusion-detection-system/**'

"module: kms":
  - changed-files:
      - any-glob-to-any-file: 'modules/kms/**'

"module: logging-bucket":
  - changed-files:
      - any-glob-to-any-file: 'modules/logging-bucket/**'

"module: looker-core":
  - changed-files:
      - any-glob-to-any-file: 'modules/looker-core/**'

"module: ncc-spoke-ra":
  - changed-files:
      - any-glob-to-any-file: 'modules/ncc-spoke-ra/**'

"module: net-address":
  - changed-files:
      - any-glob-to-any-file: 'modules/net-address/**'

"module: net-cloudnat":
  - changed-files:
      - any-glob-to-any-file: 'modules/net-cloudnat/**'

"module: net-firewall-policy":
  - changed-files:
      - any-glob-to-any-file: 'modules/net-firewall-policy/**'

"module: net-ipsec-over-interconnect":
  - changed-files:
      - any-glob-to-any-file: 'modules/net-ipsec-over-interconnect/**'

"module: net-lb-app-ext":
  - changed-files:
      - any-glob-to-any-file: 'modules/net-lb-app-ext/**'

"module: net-lb-app-ext-regional":
  - changed-files:
      - any-glob-to-any-file: 'modules/net-lb-app-ext-regional/**'

"module: net-lb-app-int":
  - changed-files:
      - any-glob-to-any-file: 'modules/net-lb-app-int/**'

"module: net-lb-app-int-cross-region":
  - changed-files:
      - any-glob-to-any-file: 'modules/net-lb-app-int-cross-region/**'

"module: net-lb-ext":
  - changed-files:
      - any-glob-to-any-file: 'modules/net-lb-ext/**'

"module: net-lb-int":
  - changed-files:
      - any-glob-to-any-file: 'modules/net-lb-int/**'

"module: net-lb-proxy-int":
  - changed-files:
      - any-glob-to-any-file: 'modules/net-lb-proxy-int/**'

"module: net-swp":
  - changed-files:
      - any-glob-to-any-file: 'modules/net-swp/**'

"module: net-vlan-attachment":
  - changed-files:
      - any-glob-to-any-file: 'modules/net-vlan-attachment/**'

"module: net-vpc":
  - changed-files:
      - any-glob-to-any-file: 'modules/net-vpc/**'

"module: net-vpc-firewall":
  - changed-files:
      - any-glob-to-any-file: 'modules/net-vpc-firewall/**'

"module: net-vpc-peering":
  - changed-files:
      - any-glob-to-any-file: 'modules/net-vpc-peering/**'

"module: net-vpn-dynamic":
  - changed-files:
      - any-glob-to-any-file: 'modules/net-vpn-dynamic/**'

"module: net-vpn-ha":
  - changed-files:
      - any-glob-to-any-file: 'modules/net-vpn-ha/**'

"module: net-vpn-static":
  - changed-files:
      - any-glob-to-any-file: 'modules/net-vpn-static/**'

"module: organization":
  - changed-files:
      - any-glob-to-any-file: 'modules/organization/**'

"module: organization-se":
  - changed-files:
      - any-glob-to-any-file: 'modules/organization-se/**'

"module: private-service-connect":
  - changed-files:
      - any-glob-to-any-file: 'modules/private-service-connect/**'

"module: project":
  - changed-files:
      - any-glob-to-any-file: 'modules/project/**'

"module: project-factory":
  - changed-files:
      - any-glob-to-any-file: 'modules/project-factory/**'

"module: projects-data-source":
  - changed-files:
      - any-glob-to-any-file: 'modules/projects-data-source/**'

"module: pubsub":
  - changed-files:
      - any-glob-to-any-file: 'modules/pubsub/**'

"module: secret-manager":
  - changed-files:
      - any-glob-to-any-file: 'modules/secret-manager/**'

"module: secure-source-manager-instance":
  - changed-files:
      - any-glob-to-any-file: 'modules/secure-source-manager-instance/**'

"module: service-directory":
  - changed-files:
      - any-glob-to-any-file: 'modules/service-directory/**'

"module: source-repository":
  - changed-files:
      - any-glob-to-any-file: 'modules/source-repository/**'

"module: spanner-instance":
  - changed-files:
      - any-glob-to-any-file: 'modules/spanner-instance/**'

"module: spanner-instance-se":
  - changed-files:
      - any-glob-to-any-file: 'modules/spanner-instance-se/**'

"module: vpc-sc":
  - changed-files:
      - any-glob-to-any-file: 'modules/vpc-sc/**'

"module: workflows":
  - changed-files:
      - any-glob-to-any-file: 'modules/workflows/**'

"module: workstation-cluster":
  - changed-files:
      - any-glob-to-any-file: 'modules/workstation-cluster/**'

"fast: 0-bootstrap":
  - changed-files:
      - any-glob-to-any-file: 'fast/stages-aw/0-bootstrap/**'

"fast: 1-resman":
  - changed-files:
      - any-glob-to-any-file: 'fast/stages-aw/1-resman/**'

"fast: 2-networking-a-fedramp":
  - changed-files:
      - any-glob-to-any-file: 'fast/stages-aw/2-networking-a-fedramp/**'

"fast: 2-networking-b-il5-ngfw":
  - changed-files:
      - any-glob-to-any-file: 'fast/stages-aw/2-networking-b-il5-ngfw/**'

"fast: 3-security":
  - changed-files:
      - any-glob-to-any-file: 'fast/stages-aw/3-security/**'

"blueprint: fedramp-high/access-context-manager":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/access-context-manager/**'

"blueprint: fedramp-high/app-engine":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/app-engine/**'

"blueprint: fedramp-high/artifact-registry":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/artifact-registry/**'

"blueprint: fedramp-high/bastion-pattern":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/bastion-pattern/**'

"blueprint: fedramp-high/bcap":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/bcap/**'

"blueprint: fedramp-high/beyondcorp":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/beyondcorp/**'

"blueprint: fedramp-high/bigtable":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/bigtable/**'

"blueprint: fedramp-high/bq-project":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/bq-project/**'

"blueprint: fedramp-high/cloud-armor":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/cloud-armor/**'

"blueprint: fedramp-high/cloud-composer-environment":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/cloud-composer-environment/**'

"blueprint: fedramp-high/cloud-functions":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/cloud-functions/**'

"blueprint: fedramp-high/cloud-ids":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/cloud-ids/**'

"blueprint: fedramp-high/cloud-run":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/cloud-run/**'

"blueprint: fedramp-high/cloud-scheduler-job":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/cloud-scheduler-job/**'

"blueprint: fedramp-high/cloud-spanner":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/cloud-spanner/**'

"blueprint: fedramp-high/cloud-translation":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/cloud-translation/**'

"blueprint: fedramp-high/cloud-workstations":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/cloud-workstations/**'

"blueprint: fedramp-high/cnap":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/cnap/**'

"blueprint: fedramp-high/compute-engine":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/compute-engine/**'

"blueprint: fedramp-high/dataflow":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/dataflow/**'

"blueprint: fedramp-high/datafusion":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/datafusion/**'

"blueprint: fedramp-high/dataproc-cluster":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/dataproc-cluster/**'

"blueprint: fedramp-high/datastore":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/datastore/**'

"blueprint: fedramp-high/document-ai":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/document-ai/**'

"blueprint: fedramp-high/firestore":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/firestore/**'

"blueprint: fedramp-high/gcs-project":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/gcs-project/**'

"blueprint: fedramp-high/gemini-enterprise":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/gemini-enterprise/**'

"blueprint: fedramp-high/gitlab":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/gitlab/**'

"blueprint: fedramp-high/gke":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/gke/**'

"blueprint: fedramp-high/gke-hardened":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/gke-hardened/**'

"blueprint: fedramp-high/kms-project":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/kms-project/**'

"blueprint: fedramp-high/network-connectivity-center":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/network-connectivity-center/**'

"blueprint: fedramp-high/postgresql":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/postgresql/**'

"blueprint: fedramp-high/private-service-connect":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/private-service-connect/**'

"blueprint: fedramp-high/pub-sub-project":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/pub-sub-project/**'

"blueprint: fedramp-high/secret-manager":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/secret-manager/**'

"blueprint: fedramp-high/shielded-vm-project":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/shielded-vm-project/**'

"blueprint: fedramp-high/vertex-mlops":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/vertex-mlops/**'

"blueprint: fedramp-high/workflows":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/fedramp-high/workflows/**'

"blueprint: il5/artifact-registry":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/il5/artifact-registry/**'

"blueprint: il5/bastion-pattern":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/il5/bastion-pattern/**'

"blueprint: il5/bcap":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/il5/bcap/**'

"blueprint: il5/bigquery":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/il5/bigquery/**'

"blueprint: il5/bq-project":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/il5/bq-project/**'

"blueprint: il5/compute-engine":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/il5/compute-engine/**'

"blueprint: il5/dataflow":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/il5/dataflow/**'

"blueprint: il5/gcs-project":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/il5/gcs-project/**'

"blueprint: il5/gke":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/il5/gke/**'

"blueprint: il5/gke-hardened":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/il5/gke-hardened/**'

"blueprint: il5/kms-project":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/il5/kms-project/**'

"blueprint: il5/postgresql":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/il5/postgresql/**'

"blueprint: il5/private-service-connect":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/il5/private-service-connect/**'

"blueprint: il5/pub-sub-project":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/il5/pub-sub-project/**'

"blueprint: il5/shielded-vm-project":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/il5/shielded-vm-project/**'

"blueprint: stand-alone/vpc-peering-project":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/stand-alone/vpc-peering-project/**'

"blueprint: third-party-solutions/gitlab":
  - changed-files:
      - any-glob-to-any-file: 'blueprints/third-party-solutions/gitlab/**'
