<?xml version="1.0"?>
<config detail-version="11.2" urldb="paloaltonetworks" version="11.2.0">
  <mgt-config>
    <users>
      <entry name="admin">
        <phash>${ password_hash }</phash>
        <permissions>
          <role-based>
            <superuser>yes</superuser>
          </role-based>
        </permissions>
        <public-key>${ ssh_pubkey }</public-key>
      </entry>
      <entry name="__openconfig">
        <phash>*</phash>
        <permissions>
          <role-based>
            <deviceadmin>
              <member>localhost.localdomain</member>
            </deviceadmin>
          </role-based>
        </permissions>
      </entry>
    </users>
    <password-complexity>
      <enabled>yes</enabled>
      <minimum-length>16</minimum-length>
    </password-complexity>
  </mgt-config>
  <shared>
    <application/>
    <application-group/>
    <service/>
    <service-group/>
    <botnet>
      <configuration>
        <http>
          <dynamic-dns>
            <enabled>yes</enabled>
            <threshold>5</threshold>
          </dynamic-dns>
          <malware-sites>
            <enabled>yes</enabled>
            <threshold>5</threshold>
          </malware-sites>
          <recent-domains>
            <enabled>yes</enabled>
            <threshold>5</threshold>
          </recent-domains>
          <ip-domains>
            <enabled>yes</enabled>
            <threshold>10</threshold>
          </ip-domains>
          <executables-from-unknown-sites>
            <enabled>yes</enabled>
            <threshold>5</threshold>
          </executables-from-unknown-sites>
        </http>
        <other-applications>
          <irc>yes</irc>
        </other-applications>
        <unknown-applications>
          <unknown-tcp>
            <destinations-per-hour>10</destinations-per-hour>
            <sessions-per-hour>10</sessions-per-hour>
            <session-length>
              <maximum-bytes>100</maximum-bytes>
              <minimum-bytes>50</minimum-bytes>
            </session-length>
          </unknown-tcp>
          <unknown-udp>
            <destinations-per-hour>10</destinations-per-hour>
            <sessions-per-hour>10</sessions-per-hour>
            <session-length>
              <maximum-bytes>100</maximum-bytes>
              <minimum-bytes>50</minimum-bytes>
            </session-length>
          </unknown-udp>
        </unknown-applications>
      </configuration>
      <report>
        <topn>100</topn>
        <scheduled>yes</scheduled>
      </report>
    </botnet>
  </shared>
  <devices>
    <entry name="localhost.localdomain">
      <network>
        <interface>
          <ethernet>
            <entry name="ethernet1/1">
              <layer3>
                <ndp-proxy>
                  <enabled>no</enabled>
                </ndp-proxy>
                <sdwan-link-settings>
                  <upstream-nat>
                    <enable>no</enable>
                    <static-ip/>
                  </upstream-nat>
                  <enable>no</enable>
                  <ipv6-enable>no</ipv6-enable>
                </sdwan-link-settings>
                <lldp>
                  <enable>no</enable>
                </lldp>
                <dhcp-client/>
                <interface-management-profile>allow-ping</interface-management-profile>
              </layer3>
            </entry>
            <entry name="ethernet1/2">
              <layer3>
                <ndp-proxy>
                  <enabled>no</enabled>
                </ndp-proxy>
                <sdwan-link-settings>
                  <upstream-nat>
                    <enable>no</enable>
                    <static-ip/>
                  </upstream-nat>
                  <enable>no</enable>
                  <ipv6-enable>no</ipv6-enable>
                </sdwan-link-settings>
                <lldp>
                  <enable>no</enable>
                </lldp>
                <dhcp-client>
                  <create-default-route>no</create-default-route>
                </dhcp-client>
                <interface-management-profile>allow-ping</interface-management-profile>
              </layer3>
            </entry>
            <entry name="ethernet1/3">
              <layer3>
                <ndp-proxy>
                  <enabled>no</enabled>
                </ndp-proxy>
                <sdwan-link-settings>
                  <upstream-nat>
                    <enable>no</enable>
                    <static-ip/>
                  </upstream-nat>
                  <enable>no</enable>
                  <ipv6-enable>no</ipv6-enable>
                </sdwan-link-settings>
                <lldp>
                  <enable>no</enable>
                </lldp>
                <dhcp-client>
                  <create-default-route>no</create-default-route>
                </dhcp-client>
                <interface-management-profile>allow-ping</interface-management-profile>
              </layer3>
            </entry>
            <entry name="ethernet1/4">
              <layer3>
                <ndp-proxy>
                  <enabled>no</enabled>
                </ndp-proxy>
                <sdwan-link-settings>
                  <upstream-nat>
                    <enable>no</enable>
                    <static-ip/>
                  </upstream-nat>
                  <enable>no</enable>
                  <ipv6-enable>no</ipv6-enable>
                </sdwan-link-settings>
                <lldp>
                  <enable>no</enable>
                </lldp>
                <dhcp-client>
                  <create-default-route>no</create-default-route>
                </dhcp-client>
                <interface-management-profile>allow-ping</interface-management-profile>
              </layer3>
            </entry>
            <entry name="ethernet1/5">
              <layer3>
                <ndp-proxy>
                  <enabled>no</enabled>
                </ndp-proxy>
                <sdwan-link-settings>
                  <upstream-nat>
                    <enable>no</enable>
                    <static-ip/>
                  </upstream-nat>
                  <enable>no</enable>
                  <ipv6-enable>no</ipv6-enable>
                </sdwan-link-settings>
                <lldp>
                  <enable>no</enable>
                </lldp>
                <dhcp-client>
                  <create-default-route>no</create-default-route>
                </dhcp-client>
                <interface-management-profile>allow-ping</interface-management-profile>
              </layer3>
            </entry>
            <entry name="ethernet1/6">
              <layer3>
                <ndp-proxy>
                  <enabled>no</enabled>
                </ndp-proxy>
                <sdwan-link-settings>
                  <upstream-nat>
                    <enable>no</enable>
                    <static-ip/>
                  </upstream-nat>
                  <enable>no</enable>
                  <ipv6-enable>no</ipv6-enable>
                </sdwan-link-settings>
                <lldp>
                  <enable>no</enable>
                </lldp>
                <dhcp-client>
                  <create-default-route>no</create-default-route>
                </dhcp-client>
                <interface-management-profile>allow-ping</interface-management-profile>
              </layer3>
            </entry>
            <entry name="ethernet1/7">
              <layer3>
                <ndp-proxy>
                  <enabled>no</enabled>
                </ndp-proxy>
                <sdwan-link-settings>
                  <upstream-nat>
                    <enable>no</enable>
                    <static-ip/>
                  </upstream-nat>
                  <enable>no</enable>
                  <ipv6-enable>no</ipv6-enable>
                </sdwan-link-settings>
                <lldp>
                  <enable>no</enable>
                </lldp>
                <dhcp-client>
                  <create-default-route>no</create-default-route>
                </dhcp-client>
                <interface-management-profile>allow-ping</interface-management-profile>
              </layer3>
            </entry>
          </ethernet>
          <loopback>
            <units>
              <entry name="loopback.1">
                <adjust-tcp-mss>
                  <enable>no</enable>
                </adjust-tcp-mss>
                <ip>
                  <entry name="100.64.0.1"/>
                </ip>
                <interface-management-profile>allow-health-check</interface-management-profile>
              </entry>
              <entry name="loopback.2">
                <adjust-tcp-mss>
                  <enable>no</enable>
                </adjust-tcp-mss>
                <ip>
                  <entry name="100.64.0.2"/>
                </ip>
                <interface-management-profile>allow-health-check</interface-management-profile>
              </entry>
            </units>
          </loopback>
        </interface>
        <profiles>
          <monitor-profile>
            <entry name="default">
              <interval>3</interval>
              <threshold>5</threshold>
              <action>wait-recover</action>
            </entry>
          </monitor-profile>
          <interface-management-profile>
            <entry name="allow-ping">
              <http>no</http>
              <https>no</https>
              <ssh>no</ssh>
              <ping>yes</ping>
            </entry>
            <entry name="allow-health-check">
              <permitted-ip>
                <entry name="35.191.0.0/16"/>
                <entry name="130.211.0.0/22"/>
                <entry name="209.85.152.0/22"/>
                <entry name="209.85.204.0/22"/>
                <entry name="169.254.169.254/32"/>
              </permitted-ip>
              <ssh>yes</ssh>
              <http>no</http>
              <https>yes</https>
            </entry>
          </interface-management-profile>
        </profiles>
        <ike>
          <crypto-profiles>
            <ike-crypto-profiles>
              <entry name="default">
                <encryption>
                  <member>aes-256-cbc</member>
                  <member>aes-128-cbc</member>
                </encryption>
                <hash>
                  <member>sha256</member>
                </hash>
                <dh-group>
                  <member>group14</member>
                </dh-group>
                <lifetime>
                  <hours>8</hours>
                </lifetime>
              </entry>
              <entry name="Suite-B-GCM-128">
                <encryption>
                  <member>aes-128-cbc</member>
                </encryption>
                <hash>
                  <member>sha256</member>
                </hash>
                <dh-group>
                  <member>group19</member>
                </dh-group>
                <lifetime>
                  <hours>8</hours>
                </lifetime>
              </entry>
              <entry name="Suite-B-GCM-256">
                <encryption>
                  <member>aes-256-cbc</member>
                </encryption>
                <hash>
                  <member>sha384</member>
                </hash>
                <dh-group>
                  <member>group20</member>
                </dh-group>
                <lifetime>
                  <hours>8</hours>
                </lifetime>
              </entry>
            </ike-crypto-profiles>
            <ipsec-crypto-profiles>
              <entry name="default">
                <esp>
                  <encryption>
                    <member>aes-256-cbc</member>
                    <member>aes-128-cbc</member>
                  </encryption>
                  <authentication>
                    <member>sha256</member>
                  </authentication>
                </esp>
                <dh-group>group14</dh-group>
                <lifetime>
                  <hours>1</hours>
                </lifetime>
              </entry>
              <entry name="Suite-B-GCM-128">
                <esp>
                  <encryption>
                    <member>aes-128-gcm</member>
                  </encryption>
                  <authentication>
                    <member>none</member>
                  </authentication>
                </esp>
                <dh-group>group19</dh-group>
                <lifetime>
                  <hours>1</hours>
                </lifetime>
              </entry>
              <entry name="Suite-B-GCM-256">
                <esp>
                  <encryption>
                    <member>aes-256-gcm</member>
                  </encryption>
                  <authentication>
                    <member>none</member>
                  </authentication>
                </esp>
                <dh-group>group20</dh-group>
                <lifetime>
                  <hours>1</hours>
                </lifetime>
              </entry>
            </ipsec-crypto-profiles>
            <global-protect-app-crypto-profiles/>
          </crypto-profiles>
        </ike>
        <qos>
          <profile>
            <entry name="default">
              <class-bandwidth-type>
                <mbps>
                  <class>
                    <entry name="class1">
                      <priority>real-time</priority>
                    </entry>
                    <entry name="class2">
                      <priority>high</priority>
                    </entry>
                    <entry name="class3">
                      <priority>high</priority>
                    </entry>
                    <entry name="class4">
                      <priority>medium</priority>
                    </entry>
                    <entry name="class5">
                      <priority>medium</priority>
                    </entry>
                    <entry name="class6">
                      <priority>low</priority>
                    </entry>
                    <entry name="class7">
                      <priority>low</priority>
                    </entry>
                    <entry name="class8">
                      <priority>low</priority>
                    </entry>
                  </class>
                </mbps>
              </class-bandwidth-type>
            </entry>
          </profile>
        </qos>
        <virtual-router>
          <entry name="default">
            <protocol>
              <bgp>
                <enable>no</enable>
                <dampening-profile>
                  <entry name="default">
                    <cutoff>1.25</cutoff>
                    <reuse>0.5</reuse>
                    <max-hold-time>900</max-hold-time>
                    <decay-half-life-reachable>300</decay-half-life-reachable>
                    <decay-half-life-unreachable>900</decay-half-life-unreachable>
                    <enable>yes</enable>
                  </entry>
                </dampening-profile>
                <routing-options>
                  <graceful-restart>
                    <enable>yes</enable>
                  </graceful-restart>
                </routing-options>
              </bgp>
              <rip>
                <enable>no</enable>
              </rip>
              <ospf>
                <enable>no</enable>
              </ospf>
              <ospfv3>
                <enable>no</enable>
              </ospfv3>
            </protocol>
            <ecmp>
              <algorithm>
                <ip-hash/>
              </algorithm>
              <enable>yes</enable>
              <symmetric-return>yes</symmetric-return>
              <max-path>4</max-path>
              <strict-source-path>yes</strict-source-path>
            </ecmp>
            <interface>
              <member>ethernet1/1</member>
              <member>ethernet1/2</member>
              <member>ethernet1/6</member>
              <member>ethernet1/7</member>
              <member>loopback.1</member>
            </interface>
            <routing-table>
              <ip>
                <static-route>
                  <entry name="default-route">
                    <nexthop>
                      <ip-address>${dmz_gateway_ip}</ip-address>
                    </nexthop>
                    <bfd>
                      <profile>None</profile>
                    </bfd>
                    <interface>ethernet1/1</interface>
                    <metric>100</metric>
                    <destination>0.0.0.0/0</destination>
                    <route-table>
                      <unicast/>
                    </route-table>
                  </entry>
                  <entry name="vdss-traffic">
                    <nexthop>
                      <ip-address>${lz_gateway_ip}</ip-address>
                    </nexthop>
                    <bfd>
                      <profile>None</profile>
                    </bfd>
                    <interface>ethernet1/2</interface>
                    <metric>10</metric>
                    <destination>10.84.0.0/16</destination>
                    <route-table>
                      <unicast/>
                    </route-table>
                  </entry>
                  <entry name="lb-check-dmz-1">
                    <nexthop>
                      <ip-address>${dmz_gateway_ip}</ip-address>
                    </nexthop>
                    <bfd>
                      <profile>None</profile>
                    </bfd>
                    <interface>ethernet1/1</interface>
                    <metric>10</metric>
                    <destination>35.191.0.0/16</destination>
                  </entry>
                  <entry name="lb-check-dmz-2">
                    <nexthop>
                      <ip-address>${dmz_gateway_ip}</ip-address>
                    </nexthop>
                    <bfd>
                      <profile>None</profile>
                    </bfd>
                    <interface>ethernet1/1</interface>
                    <metric>10</metric>
                    <destination>130.211.0.0/22</destination>
                  </entry>
                  <entry name="lb-check-vdss-1">
                    <nexthop>
                      <ip-address>${lz_gateway_ip}</ip-address>
                    </nexthop>
                    <bfd>
                      <profile>None</profile>
                    </bfd>
                    <interface>ethernet1/2</interface>
                    <metric>10</metric>
                    <destination>35.191.0.0/16</destination>
                    <route-table>
                      <unicast/>
                    </route-table>
                  </entry>
                  <entry name="tenant-traffic-1">
                    <nexthop>
                      <next-vr>env-router</next-vr>
                    </nexthop>
                    <bfd>
                      <profile>None</profile>
                    </bfd>
                    <metric>10</metric>
                    <destination>10.88.0.0/13</destination>
                    <route-table>
                      <unicast/>
                    </route-table>
                  </entry>
                  <entry name="tenant-traffic-2">
                    <nexthop>
                      <next-vr>env-router</next-vr>
                    </nexthop>
                    <bfd>
                      <profile>None</profile>
                    </bfd>
                    <metric>10</metric>
                    <destination>10.96.0.0/16</destination>
                    <route-table>
                      <unicast/>
                    </route-table>
                  </entry>
                </static-route>
              </ip>
            </routing-table>
          </entry>
          <entry name="env-router">
            <ecmp>
              <algorithm>
                <ip-modulo/>
              </algorithm>
              <enable>yes</enable>
              <symmetric-return>yes</symmetric-return>
              <max-path>4</max-path>
            </ecmp>
            <protocol>
              <bgp>
                <routing-options>
                  <graceful-restart>
                    <enable>yes</enable>
                  </graceful-restart>
                </routing-options>
                <enable>no</enable>
              </bgp>
              <rip>
                <enable>no</enable>
              </rip>
              <ospf>
                <enable>no</enable>
              </ospf>
              <ospfv3>
                <enable>no</enable>
              </ospfv3>
            </protocol>
            <interface>
              <member>ethernet1/3</member>
              <member>ethernet1/4</member>
              <member>ethernet1/5</member>
              <member>loopback.2</member>
            </interface>
            <routing-table>
              <ip>
                <static-route>
                  <entry name="lb-check-tenant-1">
                    <nexthop>
                      <ip-address>${tenant_gateway_ip}</ip-address>
                    </nexthop>
                    <bfd>
                      <profile>None</profile>
                    </bfd>
                    <interface>ethernet1/3</interface>
                    <metric>10</metric>
                    <destination>35.191.0.0/16</destination>
                    <route-table>
                      <unicast/>
                    </route-table>
                  </entry>
                  <entry name="lb-check-tenant-2">
                    <nexthop>
                      <ip-address>${tenant_gateway_ip}</ip-address>
                    </nexthop>
                    <bfd>
                      <profile>None</profile>
                    </bfd>
                    <interface>ethernet1/3</interface>
                    <metric>10</metric>
                    <destination>130.211.0.0/22</destination>
                    <route-table>
                      <unicast/>
                    </route-table>
                  </entry>
                  <entry name="lb-check-bcap-1">
                    <nexthop>
                      <ip-address>${bcap_gateway_ip}</ip-address>
                    </nexthop>
                    <bfd>
                      <profile>None</profile>
                    </bfd>
                    <interface>ethernet1/4</interface>
                    <metric>10</metric>
                    <destination>35.191.0.0/16</destination>
                    <route-table>
                      <unicast/>
                    </route-table>
                  </entry>
                  <entry name="lb-check-bcap-2">
                    <nexthop>
                      <ip-address>${bcap_gateway_ip}</ip-address>
                    </nexthop>
                    <bfd>
                      <profile>None</profile>
                    </bfd>
                    <interface>ethernet1/4</interface>
                    <metric>10</metric>
                    <destination>130.211.0.0/22</destination>
                    <route-table>
                      <unicast/>
                    </route-table>
                  </entry>
                  <entry name="lb-check-interconnect-1">
                    <nexthop>
                      <ip-address>${interconnect_gateway_ip}</ip-address>
                    </nexthop>
                    <bfd>
                      <profile>None</profile>
                    </bfd>
                    <interface>ethernet1/5</interface>
                    <metric>10</metric>
                    <destination>35.191.0.0/16</destination>
                    <route-table>
                      <unicast/>
                    </route-table>
                  </entry>
                  <entry name="lb-check-interconnect-2">
                    <nexthop>
                      <ip-address>${interconnect_gateway_ip}</ip-address>
                    </nexthop>
                    <bfd>
                      <profile>None</profile>
                    </bfd>
                    <interface>ethernet1/5</interface>
                    <metric>10</metric>
                    <destination>130.211.0.0/22</destination>
                    <route-table>
                      <unicast/>
                    </route-table>
                  </entry>
                  <entry name="default-route">
                    <nexthop>
                      <next-vr>default</next-vr>
                    </nexthop>
                    <bfd>
                      <profile>None</profile>
                    </bfd>
                    <metric>100</metric>
                    <destination>0.0.0.0/0</destination>
                    <route-table>
                      <unicast/>
                    </route-table>
                  </entry>
                  <entry name="tenant-traffic-1">
                    <nexthop>
                      <ip-address>${tenant_gateway_ip}</ip-address>
                    </nexthop>
                    <bfd>
                      <profile>None</profile>
                    </bfd>
                    <interface>ethernet1/3</interface>
                    <metric>10</metric>
                    <destination>10.88.0.0/13</destination>
                    <route-table>
                      <unicast/>
                    </route-table>
                  </entry>
                  <entry name="tenant-traffic-2">
                    <nexthop>
                      <ip-address>${tenant_gateway_ip}</ip-address>
                    </nexthop>
                    <bfd>
                      <profile>None</profile>
                    </bfd>
                    <interface>ethernet1/3</interface>
                    <metric>10</metric>
                    <destination>10.96.0.0/16</destination>
                    <route-table>
                      <unicast/>
                    </route-table>
                  </entry>
                </static-route>
              </ip>
            </routing-table>
          </entry>
        </virtual-router>
      </network>
      <deviceconfig>
        <system>
          <type>
            <dhcp-client>
              <send-hostname>yes</send-hostname>
              <send-client-id>yes</send-client-id>
              <accept-dhcp-hostname>yes</accept-dhcp-hostname>
              <accept-dhcp-domain>yes</accept-dhcp-domain>
            </dhcp-client>
          </type>
          <update-server>updates.paloaltonetworks.com</update-server>
          <update-schedule>
            <threats>
              <recurring>
                <weekly>
                  <day-of-week>wednesday</day-of-week>
                  <at>01:02</at>
                  <action>download-only</action>
                </weekly>
              </recurring>
            </threats>
          </update-schedule>
          <timezone>US/Pacific</timezone>
          <service>
            <disable-telnet>yes</disable-telnet>
            <disable-http>yes</disable-http>
          </service>
          <hostname>PA-VM</hostname>
          <device-telemetry>
            <device-health-performance>no</device-health-performance>
            <product-usage>no</product-usage>
            <threat-prevention>no</threat-prevention>
          </device-telemetry>
        </system>
        <setting>
          <config>
            <rematch>yes</rematch>
          </config>
          <management>
            <hostname-type-in-syslog>FQDN</hostname-type-in-syslog>
            <initcfg>
              <op-command-modes>mgmt-interface-swap</op-command-modes>
              <type>
                <dhcp-client>
                  <send-hostname>yes</send-hostname>
                  <send-client-id>yes</send-client-id>
                  <accept-dhcp-hostname>yes</accept-dhcp-hostname>
                  <accept-dhcp-domain>yes</accept-dhcp-domain>
                </dhcp-client>
              </type>
              <public-key>${ ssh_pubkey }</public-key>
            </initcfg>
          </management>
        </setting>
        <plugins>
          <vm_series version="5.1.0">
            <gcp-cloudwatch>
              <enabled>yes</enabled>
            </gcp-cloudwatch>
          </vm_series>
        </plugins>
      </deviceconfig>
      <vsys>
        <entry name="vsys1">
          <application/>
          <application-group/>
          <zone>
            <entry name="VDSS">
              <network>
                <layer3>
                  <member>ethernet1/2</member>
                </layer3>
              </network>
            </entry>
            <entry name="Untrust">
              <network>
                <layer3>
                  <member>ethernet1/1</member>
                </layer3>
              </network>
            </entry>
            <entry name="Tenant">
              <network>
                <layer3>
                  <member>ethernet1/3</member>
                </layer3>
              </network>
            </entry>
            <entry name="BCAP">
              <network>
                <layer3>
                  <member>ethernet1/4</member>
                </layer3>
              </network>
            </entry>
            <entry name="Interconnect">
              <network>
                <layer3>
                  <member>ethernet1/5</member>
                </layer3>
              </network>
            </entry>
            <entry name="lb-checks">
              <network>
                <layer3>
                  <member>loopback.1</member>
                  <member>loopback.2</member>
                </layer3>
              </network>
            </entry>
          </zone>
          <service/>
          <service-group/>
          <schedule/>
          <rulebase>
            <security>
              <rules>
                <entry name="allow-hc" uuid="255e86d1-445a-40e5-ba39-84f9ed7a054f">
                  <to>
                    <member>lb-checks</member>
                  </to>
                  <from>
                    <member>any</member>
                  </from>
                  <source>
                    <member>lb-checks</member>
                  </source>
                  <destination>
                    <member>any</member>
                  </destination>
                  <source-user>
                    <member>any</member>
                  </source-user>
                  <category>
                    <member>any</member>
                  </category>
                  <saas-user-list>
                    <member>any</member>
                  </saas-user-list>
                  <saas-tenant-list>
                    <member>any</member>
                  </saas-tenant-list>
                  <application>
                    <member>ssl</member>
                    <member>web-browsing</member>
                  </application>
                  <service>
                    <member>application-default</member>
                  </service>
                  <source-hip>
                    <member>any</member>
                  </source-hip>
                  <destination-hip>
                    <member>any</member>
                  </destination-hip>
                  <action>allow</action>
                  <log-start>no</log-start>
                  <log-end>yes</log-end>
                </entry>
                <entry name="allow-common-services" uuid="a4559602-dce8-41f9-8628-b4b7ab534074">
                  <to>
                    <member>any</member>
                  </to>
                  <from>
                    <member>any</member>
                  </from>
                  <source>
                    <member>any</member>
                  </source>
                  <destination>
                    <member>any</member>
                  </destination>
                  <source-user>
                    <member>any</member>
                  </source-user>
                  <category>
                    <member>any</member>
                  </category>
                  <application>
                    <member>ssl</member>
                    <member>web-browsing</member>
                    <member>ssh</member>
                    <member>ping</member>
                    <member>dns</member>
                    <member>ntp</member>
                  </application>
                  <service>
                    <member>application-default</member>
                  </service>
                  <source-hip>
                    <member>any</member>
                  </source-hip>
                  <destination-hip>
                    <member>any</member>
                  </destination-hip>
                  <action>allow</action>
                  <saas-user-list>
                    <member>any</member>
                  </saas-user-list>
                  <saas-tenant-list>
                    <member>any</member>
                  </saas-tenant-list>
                  <log-start>no</log-start>
                  <log-end>yes</log-end>
                </entry>
              </rules>
            </security>
            <nat>
              <rules>
                <entry name="vdss-untrust" uuid="ed8a6633-0706-4058-a7a2-58bd5ee71c2b">
                  <source-translation>
                    <dynamic-ip-and-port>
                      <interface-address>
                        <interface>ethernet1/1</interface>
                      </interface-address>
                    </dynamic-ip-and-port>
                  </source-translation>
                  <to>
                    <member>Untrust</member>
                  </to>
                  <from>
                    <member>VDSS</member>
                  </from>
                  <source>
                    <member>any</member>
                  </source>
                  <destination>
                    <member>any</member>
                  </destination>
                  <service>any</service>
                  <disabled>no</disabled>
                </entry>
                <entry name="ext-hc" uuid="fd407c2b-7798-43a7-b43f-ae2005935fda">
                  <dynamic-destination-translation>
                    <translated-address>loopback</translated-address>
                  </dynamic-destination-translation>
                  <to>
                    <member>Untrust</member>
                  </to>
                  <from>
                    <member>Untrust</member>
                  </from>
                  <source>
                    <member>lb-checks</member>
                  </source>
                  <destination>
                    <member>any</member>
                  </destination>
                  <service>any</service>
                  <to-interface>ethernet1/1</to-interface>
                </entry>
                <entry name="vdss-hc" uuid="99fc8954-b28d-4574-b6f7-5519641e6c02">
                  <dynamic-destination-translation>
                    <translated-address>loopback</translated-address>
                  </dynamic-destination-translation>
                  <to>
                    <member>VDSS</member>
                  </to>
                  <from>
                    <member>VDSS</member>
                  </from>
                  <source>
                    <member>lb-checks</member>
                  </source>
                  <destination>
                    <member>any</member>
                  </destination>
                  <service>any</service>
                  <to-interface>ethernet1/2</to-interface>
                </entry>
                <entry name="tenant-hc" uuid="9dd30982-996f-41c3-b976-c1e64dcb68fa">
                  <dynamic-destination-translation>
                    <translated-address>loopback2</translated-address>
                  </dynamic-destination-translation>
                  <to>
                    <member>Tenant</member>
                  </to>
                  <from>
                    <member>Tenant</member>
                  </from>
                  <source>
                    <member>lb-checks</member>
                  </source>
                  <destination>
                    <member>any</member>
                  </destination>
                  <service>any</service>
                  <to-interface>ethernet1/3</to-interface>
                </entry>
                <entry name="bcap-hc" uuid="2b8e9027-dca3-4ac5-8bd6-dcc88f7818cc">
                  <dynamic-destination-translation>
                    <translated-address>loopback2</translated-address>
                  </dynamic-destination-translation>
                  <to>
                    <member>BCAP</member>
                  </to>
                  <from>
                    <member>BCAP</member>
                  </from>
                  <source>
                    <member>lb-checks</member>
                  </source>
                  <destination>
                    <member>any</member>
                  </destination>
                  <service>any</service>
                  <to-interface>ethernet1/4</to-interface>
                </entry>
                <entry name="interconnect-hc" uuid="6d56ac72-3b04-40fd-b44c-cb2569c34d36">
                  <dynamic-destination-translation>
                    <translated-address>loopback2</translated-address>
                  </dynamic-destination-translation>
                  <to>
                    <member>Interconnect</member>
                  </to>
                  <from>
                    <member>Interconnect</member>
                  </from>
                  <source>
                    <member>lb-checks</member>
                  </source>
                  <destination>
                    <member>any</member>
                  </destination>
                  <service>any</service>
                  <to-interface>ethernet1/5</to-interface>
                </entry>
              </rules>
            </nat>
            <pbf>
              <rules/>
            </pbf>
            <default-security-rules>
              <rules>
                <entry name="intrazone-default" uuid="85326b20-cfe9-4b91-81d5-bdf03c43ddb4">
                  <action>allow</action>
                  <log-start>no</log-start>
                  <log-end>yes</log-end>
                </entry>
                <entry name="interzone-default" uuid="f8337880-d1d6-4171-b212-dd36abe087bd">
                  <action>deny</action>
                  <log-start>no</log-start>
                  <log-end>yes</log-end>
                </entry>
              </rules>
            </default-security-rules>
          </rulebase>
          <import>
            <network>
              <interface>
                <member>ethernet1/1</member>
                <member>ethernet1/2</member>
                <member>ethernet1/3</member>
                <member>ethernet1/4</member>
                <member>ethernet1/5</member>
                <member>ethernet1/6</member>
                <member>ethernet1/7</member>
                <member>loopback.1</member>
                <member>loopback.2</member>
              </interface>
            </network>
          </import>
          <address>
            <entry name="google-metadata-server">
              <ip-netmask>169.254.169.254</ip-netmask>
              <tag>
                <member>google-ip</member>
              </tag>
            </entry>
            <entry name="lb-check-1">
              <ip-netmask>35.191.0.0/16</ip-netmask>
              <tag>
                <member>google-ip</member>
              </tag>
            </entry>
            <entry name="lb-check-2">
              <ip-netmask>130.211.0.0/22</ip-netmask>
              <tag>
                <member>google-ip</member>
              </tag>
            </entry>
            <entry name="lb-check-3">
              <ip-netmask>209.85.152.0/22</ip-netmask>
              <tag>
                <member>google-ip</member>
              </tag>
            </entry>
            <entry name="lb-check-4">
              <ip-netmask>209.85.204.0/22</ip-netmask>
              <tag>
                <member>google-ip</member>
              </tag>
            </entry>
            <entry name="loopback">
              <ip-netmask>100.64.0.1</ip-netmask>
              <tag>
                <member>internal-ip</member>
              </tag>
            </entry>
            <entry name="loopback2">
              <ip-netmask>100.64.0.2</ip-netmask>
              <tag>
                <member>internal-ip</member>
              </tag>
            </entry>
          </address>
          <address-group>
            <entry name="lb-checks">
              <tag>
                <member>google-ip</member>
              </tag>
              <static>
                <member>google-metadata-server</member>
                <member>lb-check-1</member>
                <member>lb-check-2</member>
                <member>lb-check-3</member>
                <member>lb-check-4</member>
              </static>
            </entry>
          </address-group>
          <tag>
            <entry name="google-ip"/>
            <entry name="internal-ip"/>
          </tag>
        </entry>
      </vsys>
    </entry>
  </devices>
</config>