name: "Auto Release"

on:
  push:
    branches:
      - test-release-automation

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Release
        id: release
        uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        with:
          release-type: terraform
          dry-run: true
          
      - name: On Release Created
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "Successfully published release: ${{ steps.release.outputs.tag_name }}"
